# **Theoretical Questions:**

# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations
**Ans:-** NumPy (Numerical Python) is a foundational library in Python, widely used for scientific computing and data analysis due to its powerful capabilities for handling large, multi-dimensional arrays and matrices. It provides a high-performance array object called `ndarray`, along with a collection of functions for performing fast mathematical operations on these arrays. Here's an overview of its purpose and advantages:

### Purpose
1. **Efficient Numerical Computations**: NumPy is optimized for numerical calculations, making it well-suited for applications that require heavy mathematical computations, such as machine learning, data analysis, and simulations.
2. **Multi-Dimensional Arrays**: It introduces the `ndarray` structure, which allows for the creation of multi-dimensional arrays, essential for handling complex data structures like matrices.
3. **Foundation for Other Libraries**: Many data science libraries, such as Pandas, SciPy, and scikit-learn, are built on top of NumPy arrays, leveraging its optimized numerical operations.

### Advantages and Enhancements to Python's Capabilities
1. **Performance**: NumPy’s operations are implemented in C, which speeds up calculations compared to pure Python lists, particularly for large datasets. This makes it suitable for real-time data analysis.
2. **Broadcasting and Vectorization**: NumPy supports vectorized operations, allowing operations to be performed on entire arrays without the need for explicit loops. Broadcasting enables arrays of different shapes to work together, reducing memory usage and improving speed.
3. **Comprehensive Mathematical Functions**: NumPy includes a wide array of mathematical functions (like linear algebra, statistical operations, Fourier transforms), enhancing Python's capabilities for handling scientific and engineering problems.
4. **Memory Efficiency**: The ndarray uses less memory than Python lists by storing data in contiguous blocks of memory, allowing faster access and reduced memory footprint.
5. **Interoperability with Other Libraries**: NumPy arrays are compatible with numerous Python libraries, making it easier to integrate and work across scientific computing ecosystems.

Overall, NumPy provides the foundation for high-performance scientific computing in Python, supporting efficient numerical operations and enabling data scientists to work with large datasets seamlessly.


# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
**Ans:-**  In NumPy, both `np.mean()` and `np.average()` are used to calculate the central tendency of data, but they differ in functionality and application. Here's a comparison of the two functions:

### `np.mean()`
- **Purpose**: Computes the arithmetic mean of an array or along a specified axis.
- **Syntax**: `np.mean(array, axis=None, dtype=None, out=None, keepdims=<default>)`
- **Behavior**: Calculates a simple mean without any weighting. Each element in the array contributes equally to the final result.
- **Usage**: Use `np.mean()` when you want an unweighted average of all elements in an array or across a particular axis.

**Example**:


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)  # Output: 3.0
print(mean)

3.0




### `np.average()`
- **Purpose**: Computes the weighted average of an array (if weights are provided) or the simple mean if weights are not given.
- **Syntax**: `np.average(array, axis=None, weights=None, returned=False)`
- **Behavior**: Allows weighting of elements, so each element's contribution to the average can vary. If weights are not specified, it behaves similarly to `np.mean()`.
- **Usage**: Use `np.average()` when calculating a weighted mean, where different elements have different levels of importance. If `weights` are provided, each element's value is multiplied by its corresponding weight before averaging.

**Example with Weights**:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
weighted_average = np.average(arr, weights=weights)  # Output: 3.2
print(weighted_average)


3.2


**Example without Weights (works the same as np.mean()):**

In [ ]:
simple_average = np.average(arr)  # Output: 3.0
print(simple_average)


3.0




### Comparison Summary
- **Use `np.mean()`** for a straightforward arithmetic mean, as it's simpler and communicates the intent more clearly when weights are not needed.
- **Use `np.average()`** when you need to calculate a weighted mean or when you need both the average and the sum of weights (using `returned=True`).

### When to Use One Over the Other
- **Unweighted Average**: `np.mean()` is typically more concise and preferred for calculating simple averages without weights.
- **Weighted Average**: Use `np.average()` when dealing with data where certain values are more important or contribute more heavily to the result, such as in cases of sampling or probability distributions where weights indicate significance.

# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
**Ans:-** In NumPy, you can reverse an array along different axes using various methods, each tailored to specific needs. Here’s a breakdown of common methods for reversing arrays in both 1D and 2D cases:

### 1. Using Slicing (`[::-1]`)

- **1D Array**: Reverses the entire array.
- **2D Array**: Can reverse rows, columns, or both by applying slicing along different axes.

**Example for a 1D Array**:


In [ ]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print(reversed_1d) # Output: [5, 4, 3, 2, 1]

[5 4 3 2 1]


**Example for a 2D Array**:

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse rows (along axis 0)
reverse_rows = arr_2d[::-1]
# Output:
# [[7, 8, 9],
#  [4, 5, 6],
#  [1, 2, 3]]

# Reverse columns (along axis 1)
reverse_columns = arr_2d[:, ::-1]
# Output:
# [[3, 2, 1],
#  [6, 5, 4],
#  [9, 8, 7]]

# Reverse both rows and columns
reverse_both = arr_2d[::-1, ::-1]
# Output:
# [[9, 8, 7],
#  [6, 5, 4],
#  [3, 2, 1]]
reverse_both

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 2. Using `np.flip()`
np.flip() allows for reversal along any specified axis and is often more flexible and explicit.

- **Syntax:** `np.flip(array, axis)`
- **axis:** Specifies which axis to flip. If not provided, it reverses along all axes.

**Example for a 1D Array:**

In [ ]:
reversed_1d = np.flip(arr_1d)  # Output: [5, 4, 3, 2, 1]
reversed_1d

array([5, 4, 3, 2, 1])

**Example for a 2D Array:**

In [ ]:
# Reverse along axis 0 (rows)
reverse_rows = np.flip(arr_2d, axis=0)
# Output:
# [[7, 8, 9],
#  [4, 5, 6],
#  [1, 2, 3]]

# Reverse along axis 1 (columns)
reverse_columns = np.flip(arr_2d, axis=1)
# Output:
# [[3, 2, 1],
#  [6, 5, 4],
#  [9, 8, 7]]
reverse_columns
reverse_rows


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])



### 3. Using `np.fliplr()` and `np.flipud()`

For 2D arrays specifically, `np.fliplr()` and `np.flipud()` are convenient functions for reversing along the horizontal and vertical axes, respectively.

- **`np.fliplr()`**: Reverses the array along the left-right (horizontal) axis.
- **`np.flipud()`**: Reverses the array along the up-down (vertical) axis.

**Example for a 2D Array**:


In [ ]:
# Reverse left-right (horizontal axis)
reverse_lr = np.fliplr(arr_2d)
# Output:
# [[3, 2, 1],
#  [6, 5, 4],
#  [9, 8, 7]]

# Reverse up-down (vertical axis)
reverse_ud = np.flipud(arr_2d)
# Output:
# [[7, 8, 9],
#  [4, 5, 6],
#  [1, 2, 3]]

### Summary
- **1D Arrays**: Use slicing (`[::-1]`) or `np.flip()`.
- **2D Arrays**: Use slicing (`[::-1]`), `np.flip()` for any axis, or `np.fliplr()`/`np.flipud()` for convenient horizontal or vertical flips.

These methods allow flexibility for reversing arrays along specific axes, making them useful in various applications where array orientation matters.

# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
**Ans:-**In NumPy, the data type (or `dtype`) of elements within an array is essential for both memory management and computational performance, as it defines how much memory each element consumes and what operations are possible on the data.

### Determining the Data Type of Elements in a NumPy Array

1. **Using `array.dtype`**:
   - The `dtype` attribute of a NumPy array provides the data type of its elements.
   - **Example**:
     



In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)


int64




2. **Using `np.asarray()` with `dtype` argument**:
   - When creating or converting an array, you can specify the desired data type using the `dtype` argument to ensure it meets your requirements.
   - **Example**:
     

In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)  # Output: float32


float32




### Importance of Data Types in Memory Management and Performance

1. **Memory Management**:
   - **Memory Efficiency**: The choice of `dtype` determines the amount of memory each element occupies. For example, `int32` occupies 4 bytes per element, whereas `float64` occupies 8 bytes. Selecting an appropriate `dtype` can significantly reduce memory consumption.
   - **Scalability**: When working with large datasets, using a smaller data type (like `int16` instead of `int64`) can drastically reduce memory usage, making the program scalable and more efficient in terms of memory footprint.

2. **Performance**:
   - **Processing Speed**: Smaller data types are often faster to process because they require less memory to load and perform computations on. For example, `float32` calculations are generally faster than `float64` on most architectures.
   - **Type-Specific Operations**: Certain operations are optimized for specific data types. For instance, integer types are more efficient for indexing and bitwise operations, whereas floating-point types are better suited for mathematical functions and transformations.

In summary, understanding and choosing the right data type in NumPy is crucial for efficient memory usage and performance optimization, especially when dealing with large-scale data and computational tasks.

# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
**Ans:-**In NumPy, **ndarrays** (short for *N-dimensional arrays*) are a core data structure designed to store and operate on large, multi-dimensional datasets efficiently. They provide a significant advantage over standard Python lists, especially for numerical and scientific computations.

### Key Features of `ndarray`
1. **Multi-Dimensional Support**: `ndarray` can handle data in multiple dimensions (1D, 2D, 3D, and higher), which makes it versatile for representing complex data like matrices, images, or large datasets.
  
2. **Fixed Data Type**: All elements in an `ndarray` have the same data type, specified at the time of array creation. This uniformity allows for optimized memory storage and computation.

3. **Efficient Memory Layout**: `ndarray` stores data in contiguous blocks of memory, which enables faster access and efficient manipulation. This layout also allows vectorized operations and broadcasting, making calculations quicker.

4. **Broadcasting**: NumPy allows operations between arrays of different shapes through broadcasting, a mechanism that automatically expands arrays to compatible shapes for element-wise operations, avoiding the need for explicit loops.

5. **Vectorized Operations**: Operations on `ndarray` are applied element-wise without the need for loops, significantly improving computation speed over Python lists. This includes operations like addition, subtraction, and even complex mathematical transformations.

6. **Shape and Reshaping**: `ndarray` has attributes like `shape` and `size` that provide information on its structure. Arrays can be reshaped using methods like `reshape()` and `transpose()`, allowing flexibility in data manipulation.

7. **Indexing and Slicing**: NumPy arrays support advanced slicing and indexing (including Boolean and fancy indexing), making it easy to access and modify specific elements, rows, or columns of the array.

### Differences Between `ndarray` and Python Lists

| Feature                  | `ndarray` in NumPy                          | Python Lists                           |
|--------------------------|---------------------------------------------|----------------------------------------|
| **Data Type**            | Fixed, uniform data type                    | Can contain mixed data types           |
| **Multi-Dimensional**    | Supports multi-dimensional arrays (nD)      | Primarily 1D, needs nested lists for 2D or 3D |
| **Memory Efficiency**    | Stores data in contiguous memory blocks     | Data stored as objects in pointers     |
| **Performance**          | Faster, supports vectorized operations      | Slower due to interpreted loop processing|
| **Operations**           | Element-wise and broadcasting supported     | Requires loops for element-wise operations |
| **Reshaping**            | Easily reshaped with `reshape` or `transpose` | No built-in reshaping methods          |

### Example of `ndarray` Creation and Operation




In [ ]:
import numpy as np

# Creating a 2D ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Checking data type, shape, and performing a vectorized operation
print(arr.dtype)      # Output: dtype('int64') or dtype('int32') depending on system
print(arr.shape)      # Output: (2, 3)
print(arr * 2)        # Output: [[ 2,  4,  6], [ 8, 10, 12]]


int64
(2, 3)
[[ 2  4  6]
 [ 8 10 12]]


In summary, ndarray provides a more powerful, memory-efficient, and faster alternative to Python lists, particularly suited for numerical and scientific applications.

# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
**Ans:-**NumPy arrays offer significant performance benefits over Python lists, especially when handling large-scale numerical operations. Here’s an analysis of the key reasons why NumPy arrays outperform lists in this context:

### 1. **Memory Efficiency**
   - **Fixed Data Type**: NumPy arrays require each element to be of the same data type, which enables them to store elements in a contiguous block of memory. This reduces memory overhead compared to Python lists, which store elements as individual objects with additional metadata.
   - **Reduced Memory Footprint**: Because of the consistent data type, a NumPy array typically consumes less memory than a Python list with the same elements. This is particularly valuable when working with large datasets.

### 2. **Contiguous Memory Allocation**
   - **Cache Optimization**: NumPy arrays are stored in contiguous memory blocks, enhancing CPU cache efficiency. The CPU can load larger chunks of data into memory at once, which speeds up access and manipulation compared to the scattered memory storage of Python lists.
   - **Low-Level Optimization**: NumPy is implemented in C, which allows it to take advantage of low-level optimizations like SIMD (Single Instruction, Multiple Data) operations. These optimizations make NumPy faster for element-wise operations.

### 3. **Vectorized Operations and Broadcasting**
   - **Avoiding Loops**: NumPy supports vectorized operations, which allow element-wise operations to be applied directly to arrays without explicit loops. In contrast, applying operations across a Python list would typically require using a `for` loop, which is slower in Python.
   - **Broadcasting**: NumPy can automatically align arrays of different shapes to perform operations, avoiding the need to reshape or replicate data manually. This reduces memory usage and improves computational speed.

  **Example:**
   

In [ ]:
import numpy as np

# Element-wise addition in NumPy
arr = np.array([1, 2, 3, 4])
result = arr + 2  # Each element is incremented by 2

# Python list alternative
lst = [1, 2, 3, 4]
result_lst = [x + 2 for x in lst]  # Loop-based operation



### 4. **Efficient Mathematical Functions**
   - **Built-in Mathematical Operations**: NumPy provides a wide range of optimized mathematical functions (e.g., `np.sum`, `np.mean`, `np.dot`) that are implemented at the C level. These functions are faster than performing similar operations with Python’s built-in functions or custom loops.
   - **Reduced Function Overhead**: Since the functions operate directly on `ndarrays`, there’s less function call overhead compared to applying Python functions on list elements.

### 5. **Scalability for Large Datasets**
   - **Memory Mapping for Large Data**: NumPy supports memory mapping, which allows efficient access to large datasets stored on disk without loading the entire dataset into RAM. Python lists lack this capability, making NumPy more scalable for large data.
   - **Parallel Processing**: NumPy can leverage libraries like BLAS and LAPACK, which support multi-threaded operations for certain functions. This allows NumPy to utilize multiple CPU cores, enhancing performance further for large arrays.

### Performance Example
Here’s a comparison to illustrate the performance difference between a NumPy array and a Python list for a large-scale numerical operation:



In [ ]:
import numpy as np
import time

# Large dataset size
size = 10**6

# Using Python lists
lst = list(range(size))
start_time = time.time()
result_lst = [x * 2 for x in lst]
print("Time taken with list:", time.time() - start_time)

# Using NumPy arrays
arr = np.arange(size)
start_time = time.time()
result_arr = arr * 2  # Vectorized operation
print("Time taken with NumPy array:", time.time() - start_time)


Time taken with list: 0.09913420677185059
Time taken with NumPy array: 0.011674642562866211




### Summary of Benefits
NumPy arrays are optimized for:
- **Memory usage** through fixed data types and contiguous storage.
- **Speed** via vectorized operations and CPU optimizations.
- **Scalability** due to efficient memory mapping and support for large datasets.

In numerical computing, these advantages make NumPy arrays a more powerful and efficient choice than Python lists, especially for large-scale operations.

# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

**Ans:-** In NumPy, `vstack()` and `hstack()` are functions used to concatenate arrays along different axes:

- **`vstack()` (Vertical Stack)**: Stacks arrays vertically (row-wise).
- **`hstack()` (Horizontal Stack)**: Stacks arrays horizontally (column-wise).

Both functions require the arrays to have compatible shapes for stacking in their respective directions.

### 1. `np.vstack()`
- **Purpose**: Vertically stacks arrays along rows, adding new rows to the bottom.
- **Shape Requirement**: Arrays must have the same number of columns (second dimension).

**Example**:




In [1]:
import numpy as np

# Creating two 2D arrays with the same number of columns
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Using vstack to stack vertically
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 2. `np.hstack()`
- **Purpose**: Horizontally stacks arrays along columns, adding new columns to the right.
- **Shape Requirement**: Arrays must have the same number of rows (first dimension).

**Example**:




In [2]:
# Creating two 2D arrays with the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Using hstack to stack horizontally
result_hstack = np.hstack((arr1, arr2))
print(result_hstack)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


### Comparison Summary

| Function       | Purpose            | Shape Compatibility Requirements  | Example Output |
|----------------|--------------------|-----------------------------------|----------------|
| **`vstack()`** | Vertical stacking  | Same number of columns            | Adds rows      |
| **`hstack()`** | Horizontal stacking| Same number of rows               | Adds columns   |

In summary, `vstack()` stacks arrays by rows, while `hstack()` stacks them by columns. Choosing one over the other depends on whether you want to add new rows or columns to the arrays.

# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
**Ans:-** In NumPy, `fliplr()` and `flipud()` are methods used to flip (or reverse) the elements of arrays along different axes:

- **`fliplr()`**: Flips the array left-to-right (horizontally).
- **`flipud()`**: Flips the array upside-down (vertically).

These functions are particularly useful for image processing, data manipulation, or any application where you need to mirror or reverse array content along a specific axis.

### 1. `np.fliplr()`
- **Purpose**: Flips the array horizontally, reversing the order of columns.
- **Effect**: Each row remains in place, but the order of columns is reversed for all rows.
- **Applicable**: Only to 2D arrays or higher (requires at least 2 dimensions).
  
**Example**:
```python
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Applying fliplr
result_fliplr = np.fliplr(arr)
print(result_fliplr)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]
```

### 2. `np.flipud()`
- **Purpose**: Flips the array vertically, reversing the order of rows.
- **Effect**: Each column remains in place, but the order of rows is reversed for all columns.
- **Applicable**: Works with both 1D and 2D arrays.

**Example**:
```python
# Applying flipud
result_flipud = np.flipud(arr)
print(result_flipud)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
```

### Effects on Different Array Dimensions

1. **1D Arrays**:
   - Only `flipud()` can be used, which will reverse the 1D array as a whole.
   - **Example**:
     ```python
     arr_1d = np.array([1, 2, 3])
     print(np.flipud(arr_1d))  # Output: [3 2 1]
     ```
2. **2D Arrays**:
   - `fliplr()` flips horizontally (left-to-right).
   - `flipud()` flips vertically (upside-down).

3. **3D Arrays or Higher**:
   - Both functions will operate on the last two dimensions only (i.e., they treat each "layer" of a 3D array as a 2D array and apply the flipping accordingly).

### Comparison Summary

| Function     | Axis of Flip                  | Minimum Dimensions | Effect on 2D Array  |
|--------------|-------------------------------|--------------------|----------------------|
| `fliplr()`   | Horizontal (left-to-right)    | 2D                 | Reverses columns     |
| `flipud()`   | Vertical (top-to-bottom)      | 1D                 | Reverses rows        |

In summary, `fliplr()` and `flipud()` offer array manipulation tools along different axes, with `fliplr()` flipping along the horizontal axis and `flipud()` flipping along the vertical axis.


# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
**Ans:-** The `array_split()` method in NumPy is used to split an array into multiple sub-arrays. This function is flexible and can handle cases where the array cannot be evenly divided, making it especially useful when you need to split an array into a specified number of parts, regardless of the exact divisibility.

### Functionality of `np.array_split()`
- **Purpose**: Splits an array into a specified number of sub-arrays along a given axis.
- **Syntax**: `np.array_split(array, num_splits, axis=0)`
  - `array`: The array to split.
  - `num_splits`: The desired number of sub-arrays.
  - `axis`: The axis along which to split the array (default is `0` for row-wise splitting).

### Handling Uneven Splits
When the array cannot be evenly split, `array_split()` distributes the remainder across the initial sub-arrays. This means that the first few sub-arrays will have one more element than the others.

For example, if you try to split an array with 10 elements into 3 parts, `array_split()` will create arrays with sizes `[4, 3, 3]` instead of `[3, 3, 3]`.

**Example of Uneven Split**:
```python
import numpy as np

# Creating a 1D array with 10 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Splitting into 3 parts
result = np.array_split(arr, 3)
print(result)
# Output:
# [array([1, 2, 3, 4]), array([5, 6, 7]), array([8, 9, 10])]
```

### Example with a 2D Array
If the array is 2D, `array_split()` will split it along rows (axis=0) by default but can be customized to split along columns (axis=1).

**Example**:
```python
# Creating a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Splitting into 3 parts along columns (axis=1)
result_2d = np.array_split(arr_2d, 3, axis=1)
print(result_2d)
# Output:
# [array([[1, 2],
#         [5, 6]]),
#  array([[3],
#         [7]]),
#  array([[4],
#         [8]])]
```

### Comparison with `np.split()`
- `np.split()` requires the array to be evenly divisible by the specified number of splits, otherwise it raises an error.
- `np.array_split()`, however, allows uneven splits, making it more flexible for cases where an exact division isn’t possible.

### Summary
- **Flexible Splitting**: `array_split()` allows for splitting arrays even when the split isn’t even.
- **Remainder Handling**: Distributes any remainder among the first few sub-arrays to accommodate uneven splits.
  
`array_split()` is a versatile method, ideal for splitting arrays of any dimension or size when exact divisibility isn’t required.

# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
**Ans:-** Vectorization and broadcasting are two core concepts in NumPy that enable efficient and optimized array operations. They help avoid explicit loops and allow element-wise operations directly on entire arrays, making computations faster and more memory-efficient.

### 1. Vectorization
- **Concept**: Vectorization is the process of applying operations directly on entire arrays (vectors) without the need for explicit loops. NumPy achieves this by implementing mathematical operations at a low level in C, which are then applied to entire arrays as single operations in Python.
- **Performance Benefit**: By replacing Python loops with vectorized operations, NumPy reduces the overhead associated with loop iterations and function calls. Vectorized operations execute at compiled speeds rather than interpreted Python speeds, which can be significantly slower.
  
**Example**:
```python
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Vectorized operation to double each element
result = arr * 2  # No explicit loop required
print(result)
# Output: [ 2  4  6  8 10]
```
Without vectorization, this operation would require a `for` loop, which is slower and less concise.

### 2. Broadcasting
- **Concept**: Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes and sizes by automatically expanding smaller arrays to match the shape of larger arrays. Broadcasting follows specific rules to determine how arrays with different dimensions are aligned.
- **Rules of Broadcasting**:
  1. If two arrays differ in the number of dimensions, the shape with fewer dimensions is padded with ones on its left side.
  2. If the shape of the arrays doesn’t match along any dimension, NumPy attempts to stretch the smaller array to match the larger one along those dimensions.
  3. If alignment is impossible (e.g., incompatible shapes that cannot be broadcasted), NumPy will raise an error.

- **Performance Benefit**: Broadcasting avoids the need to create expanded copies of arrays, reducing memory usage and speeding up computation. Instead of replicating smaller arrays, broadcasting applies operations as if the arrays were the same size, saving both time and space.

**Example**:
```python
# Create two arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([1, 2, 3])               # Shape (3,)

# Broadcasting in action: arr2 is "stretched" to match arr1
result = arr1 + arr2
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]
```
Here, `arr2` is broadcasted across `arr1` without needing explicit loops or reshaping.

### How Vectorization and Broadcasting Contribute to Efficient Array Operations
- **Reduced Python Overhead**: Vectorization minimizes Python-level loops, which are generally slower because they run in the interpreter.
- **Optimized Memory Usage**: Broadcasting avoids creating redundant data copies by "stretching" smaller arrays logically rather than physically.
- **Faster Computations**: Operations on arrays are implemented in optimized C code behind the scenes, enabling faster calculations than traditional Python for-loops.
- **Concise Code**: Both techniques allow for more readable, compact code, making array operations simpler and more intuitive.

### Example of Combined Vectorization and Broadcasting
Consider adding a scalar to a 2D array:
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Adding 10 to each element (vectorization + broadcasting)
result = arr + 10
print(result)
# Output:
# [[11 12 13]
#  [14 15 16]]
```

Here, the scalar `10` is broadcasted across `arr`, and the addition is vectorized, providing both efficient memory usage and fast computation.

In summary, **vectorization** and **broadcasting** are powerful tools in NumPy that enable efficient, high-performance computations by avoiding explicit loops, minimizing memory usage, and optimizing array operations at a low level.

# **Practical Questions:**

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [3]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns by transposing the array
transposed_array = np.transpose(array)

print("Original Array:")
print(array)
print("\nTransposed Array (Rows and Columns Interchanged):")
print(transposed_array)


Original Array:
[[97 90 62]
 [59 17 77]
 [20 67 39]]

Transposed Array (Rows and Columns Interchanged):
[[97 59 20]
 [90 17 67]
 [62 77 39]]


# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("1D Array:")
print(array_1d)
print("\nReshaped to 2x5 Array:")
print(array_2x5)
print("\nReshaped to 5x2 Array:")
print(array_5x2)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [5]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:")
print(array_4x4)
print("\n6x6 Array with Zero Border:")
print(array_6x6)


Original 4x4 Array:
[[0.54987202 0.25449692 0.98298938 0.44716034]
 [0.35464836 0.21165434 0.07153163 0.96670981]
 [0.33321724 0.42775781 0.37606441 0.79979741]
 [0.18148116 0.84907931 0.14722892 0.79660799]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.54987202 0.25449692 0.98298938 0.44716034 0.        ]
 [0.         0.35464836 0.21165434 0.07153163 0.96670981 0.        ]
 [0.         0.33321724 0.42775781 0.37606441 0.79979741 0.        ]
 [0.         0.18148116 0.84907931 0.14722892 0.79660799 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [6]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array_integers)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


In [7]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

print("Original Array:")
print(string_array)

print("\nUppercase Transformation:")
print(uppercase_array)

print("\nLowercase Transformation:")
print(lowercase_array)

print("\nTitle Case Transformation:")
print(titlecase_array)

print("\nCapitalize Transformation:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']

Capitalize Transformation:
['Python' 'Numpy' 'Pandas']


# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [8]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words_array = np.array([' '.join(word) for word in words_array])

print("Original Array:")
print(words_array)

print("\nArray with Spaces Between Characters:")
print(spaced_words_array)


Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [9]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [10]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


In [11]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

print("Random Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers:
[387   3 499 380 989 384 728  10 533 932 913 250 167 901 103 398  80  57
  92 831 555 457   4 482 730 904 194 447 371 626 884 694 151 780   1 817
 139 437 919 700 648  30 128 582 148 123 631 400 602  15 986 768 410  24
 276 930 365  84 831 411 548 789 424 180 337  49 562 226 554 175 293 430
 146 219 174  86  61 257 365 566 790 317 638 641 455 758 364 737 553 948
 881 579 541 168 311 948 454 393 710 502]

Prime Numbers in the Array:
[  3 499 167 103 457 151 139 919 631 337 293  61 257 317 641 881 541 311]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.



In [12]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# Let's assume temperatures range from 0 to 40 degrees Celsius
daily_temperatures = np.random.randint(0, 41, size=30)

# Calculate weekly averages (4 weeks)
# Reshape the array into a 4x7 matrix for the 4 weeks, ignoring the last two days
weekly_averages = np.mean(daily_temperatures[:28].reshape(4, 7), axis=1)

print("Daily Temperatures for a Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for a Month:
[ 9 34 24 32  9 39 10 11 19 39  3 30  6 34 29  2  3 35 25 27 21  8 18 38
 29  8  8  1 10  7]

Weekly Averages:
[22.42857143 20.28571429 20.28571429 15.71428571]
